-- MySQL Script generated by MySQL Workbench
-- Fri Jan  3 22:29:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectG
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `projectG` DEFAULT CHARACTER SET utf8mb3 ;
USE `projectG` ;

-- -----------------------------------------------------
-- Table `projectG`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectG`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idrol`),
  UNIQUE INDEX `idrol_UNIQUE` (`idrol` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projectG`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectG`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  INDEX `fk_user_rol_idx` (`rol_idrol` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_user_rol`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `projectG`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projectG`.`coupon_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectG`.`coupon_book` (
  `idcoupon_book` INT NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(45) NOT NULL,
  `total_coupons` INT NOT NULL,
  `remaining_coupons` INT NOT NULL,
  `expiration_date` DATETIME NOT NULL,
  `purchase_date` DATETIME NOT NULL,
  `user_iduser` INT NOT NULL,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcoupon_book`),
  UNIQUE INDEX `idcoupon_book_UNIQUE` (`idcoupon_book` ASC) VISIBLE,
  INDEX `fk_coupon_book_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_coupon_book_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `projectg`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projectG`.`class_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectG`.`class_schedule` (
  `idclass_schedule` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `capacity` INT NOT NULL,
  `available_spots` INT NOT NULL,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idclass_schedule`),
  UNIQUE INDEX `idclass_schedule_UNIQUE` (`idclass_schedule` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectG`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectG`.`reservation` (
  `idreservation` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `class_schedule_idclass_schedule` INT NOT NULL,
  `coupon_book_idcoupon_book` INT NOT NULL,
  `reservation_date` DATETIME NOT NULL,
  `is_canceled` INT NOT NULL DEFAULT 0,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreservation`),
  UNIQUE INDEX `idreservation_UNIQUE` (`idreservation` ASC) VISIBLE,
  INDEX `fk_reservation_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_reservation_class_schedule1_idx` (`class_schedule_idclass_schedule` ASC) VISIBLE,
  INDEX `fk_reservation_coupon_book1_idx` (`coupon_book_idcoupon_book` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `projectg`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_class_schedule1`
    FOREIGN KEY (`class_schedule_idclass_schedule`)
    REFERENCES `projectG`.`class_schedule` (`idclass_schedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_coupon_book1`
    FOREIGN KEY (`coupon_book_idcoupon_book`)
    REFERENCES `projectG`.`coupon_book` (`idcoupon_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `projectG` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
